A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    # path('cart/', include('cart.urls', namespace='cart')),
    # path('store/', include('store.urls', namespace='store')),
    # path('checkout/', include('checkout.urls', namespace='checkout')),
    path('', include('core.urls', namespace='core')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit/', views.UserProfileEditView.as_view(), name='profile_edit'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import CustomUserManager


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    full_name = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    def __str__(self):
        return self.email

    @staticmethod
    def has_perm(perm, obj=None):
        return True

    @staticmethod
    def has_module_perms(app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='accounts/uploads/images/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.user.full_name

    @property
    def avatar_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        return None

accounts/forms.py
from django import forms
from .models import User, Profile
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'full_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'full_name', 'password')

    def clean_password(self):
        return self.initial['password']


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    full_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ProfileForm(forms.ModelForm):
    email = forms.EmailField()
    full_name = forms.CharField(max_length=50)

    class Meta:
        model = Profile
        fields = ('avatar', 'location', 'bio', 'birth_date')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserLoginForm, UserRegistrationForm, UserCreationForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import User
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('core:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, email=cd['email'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'You have successfully logged in!', 'success')
                return redirect('core:home')
            else:
                messages.error(request, 'Your email or password is incorrect!', 'danger')
        return render(request, self.template_name, {'form': form})


class UserRegistrationView(View):
    form_class = UserCreationForm
    template_name = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('core:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(cd['email'], cd['full_name'], cd['password2'])
            user.save()
            messages.success(request, 'You have successfully registered!', 'success')
            return redirect('accounts:login')

        messages.error(request, 'Oops! Something went wrong!', 'danger')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'You have successfully logged out!', 'success')
        return redirect('core:home')


class UserProfileView(LoginRequiredMixin, View):
    template_name = 'accounts/profile.html'

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        return render(request, self.template_name, {'user': user})


class VerifyEmailView(LoginRequiredMixin, View):
    pass


class SendVerifyCodeView(LoginRequiredMixin, View):
    pass


class ForgotPasswordView(LoginRequiredMixin, View):
    pass


class ResetPasswordView(LoginRequiredMixin, View):
    pass


class ChangePasswordView(LoginRequiredMixin, View):
    pass


class ChangeEmailView(LoginRequiredMixin, View):
    pass


class UserProfileEditView(LoginRequiredMixin, View):
    form_class = ProfileForm
    template_name = 'accounts/profile_edit.html'

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        form = self.form_class(instance=user.profile, initial={'email': user.email, 'full_name': user.full_name})
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        form = self.form_class(request.POST, instance=user.profile)
        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data['email']
            request.user.full_name = form.cleaned_data['full_name']
            request.user.save()
            messages.success(request, 'Your profile has been updated!', 'success')
            return redirect('accounts:profile', pk=pk)
        messages.error(request, 'Oops! Something went wrong!', 'danger')
        return render(request, self.template_name, {'form': form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">
<!--	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">-->
{% endblock %}



{% block content %}
<!--test-->
<!--    <div class="container">-->
<!--      <h1>Sign In</h1>-->
<!--      <form>-->
<!--        <div class="form-control">-->
<!--          <input type="text" required />-->
<!--          <label>Your Email</label>-->
<!--        </div>-->
<!--        <div class="form-control">-->
<!--          <input type="password" required />-->
<!--          <label>Your Password</label>-->
<!--        </div>-->
<!--        <button class="btn">Submit</button>-->
<!--        <p class="text">Don't have an account? <a href="#">Create Account</a></p>-->
<!--      </form>-->
<!--    </div>-->


<!--test-->

<br><br>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								{{ form.password }}
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block custom_js %}
	<script type="text/javascript" src="{% static 'accounts/js/register.js' %}"></script>
<!--	<script type="text/javascript" src="{% static 'accounts/js/script.js' %}"></script>-->
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'accounts:profile_edit' request.user.id %}" class="nav-link active" aria-current="page" >Edit</a>
    <a href=""><img src="{{ request.user.avatar_url }}" alt=""></a>

    <p>My Profile</p>
    <hr>
    <p>{{ user.full_name }}</p>
    <p>{{ user.profile.bio }}</p>
    <img src="{{ user.profile.avatar_url }}" alt="">

{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
<!--    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/register.css' %}">-->
{% endblock %}
    
{% block content %}
    <br><br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit">
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/register.css' %}">
{% endblock %}

{% block content %}
<br><br>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="" novalidate>
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.full_name }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block custom_js %}
	<script src="{% static 'accounts/js/register.js' %}"></script>
{% endblock %}





<!--<head>-->
<!--	<title>Login</title>-->
<!--	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
<!--	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
<!--	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">-->