A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    # path('cart/', include('cart.urls', namespace='cart')),
    # path('store/', include('store.urls', namespace='store')),
    # path('checkout/', include('checkout.urls', namespace='checkout')),
    path('', include('core.urls', namespace='core')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit/', views.UserProfileEditView.as_view(), name='profile_edit'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.ArticleView.as_view(), name='articles'),
    path('<int:pk>/<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'core:home' %}">CoffeeInRider</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:articles' %}">Article</a>
        </li>
      </ul>
      <div class="form-inline my-2 my-lg-0 ">
        {% if request.user.is_authenticated %}
          <a href="{% url 'accounts:profile' request.user.id %}" class="nav-link active" aria-current="page" >Profile</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-warning" >Logout</a>
        {% else %}
          <a href="{% url 'accounts:login' %}" class="btn btn-warning" >Login</a>
        {% endif %}
      </div>

    </div>
</nav>